import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";
import { Button } from "@/components/ui/button";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSideBar from "@/components/appSideBar";
import { getSession } from "@/auth"
import Providers from "@/providers"
import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

  const session = await getSession()

  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet" />
      </Head>
      <body className="dark flex flex-col h-screen font-inter">
        <Providers session={session}>
          <SidebarProvider>
            <AppSideBar />
            <main className="flex-1 flex flex-col overflow-hidden">
              <Header />
              <div className="p-4 pt-5 overflow-auto h-full">
                {children}
              </div>
            </main>
          </SidebarProvider>
        </Providers>
      </body>
    </html >
  );
}
